/*
 * Game.java
 *
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 *
 * Copyright 2008-2014 supareno
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.supareno.pgnparser.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Data
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JacksonXmlRootElement(localName = "game")
public class Game {

    protected String event = "";
    protected String site = "";
    protected String date = "";
    protected String round = "";
    protected String white = "";
    protected String black = "";
    protected String result = "";
    protected String whiteTitle = "";
    protected String whiteElo = "";
    protected String whiteUSCF = "";
    protected String whiteNA = "";
    protected String whiteType = "";
    protected String blackTitle = "";
    protected String blackElo = "";
    protected String blackUSCF = "";
    protected String blackNA = "";
    protected String blackType = "";
    protected String eventDate = "";
    protected String eventSponsor = "";
    protected String section = "";
    protected String stage = "";
    protected String board = "";
    protected String opening = "";
    protected String variation = "";
    protected String subVariation = "";
    protected String eco = "";
    protected String nic = "";
    protected String time = "";
    @JacksonXmlProperty(localName = "UTCTime")
    protected String utcTime = "";
    @JacksonXmlProperty(localName = "UTCDate")
    protected String utcDate = "";
    protected String timeControl = "";
    protected String setUp = "";
    @JacksonXmlProperty(localName = "FEN")
    protected String fen = "";
    protected String termination = "";

    //@JacksonXmlElementWrapper(useWrapping = false)
    @JacksonXmlElementWrapper
    protected List<Hit> hits=new ArrayList<>();
}
